# Generated by Django 4.1.7 on 2023-02-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_readingmaterial_contenttopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_level', models.CharField(max_length=10)),
                ('short_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('right_option', models.CharField(max_length=20)),
                ('wrong_option1', models.CharField(max_length=20)),
                ('wrong_option2', models.CharField(max_length=20)),
                ('wrong_option3', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.course')),
            ],
        ),
    ]
