# Generated by Django 4.1.7 on 2023-02-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_course_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmaterial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.course'),
        ),
    ]
