# Generated by Django 4.1.7 on 2023-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_student_remove_readingmaterial_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingproblem',
            name='problem',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='programmingproblem',
            name='sample_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingproblem',
            name='sample_output',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
